on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'New version number'
        required: true
        default: '1.3.5'

jobs:
  update-version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: airdata/docker-jenkins-stack  # Replace with target repository
          token: ${{ secrets.PAT_TOKEN }}
          path: docker-jenkins-stack
          
      - name: Add text to file
        run: |
          python -c '
          import os
          
          # Get inputs
          new_version = """${{ github.event.inputs.new_text }}"""
          
          file_path = "docker-jenkins-stack/jenkins-master/Dockerfile"
          
          # Read existing content
          with open(file_path, "r") as file:
              content = file.read()
              lines = content.splitlines()
          
          if add_mode == "append":
              # Add newline if file doesnt end with one
              if content and not content.endswith("\n"):
                  new_text = "\n" + new_text
              
              # Append text
              with open(file_path, "a") as file:
                  file.write(new_text + "\n")
                  
          else:  # insert mode
              new_lines = []
              found = False
              
              # Insert after specific line
              for line in lines:
                  new_lines.append(line)
                  if insert_after in line:
                      new_lines.append(new_text)
                      found = True
              
              # If line not found, append at end
              if not found:
                  new_lines.append(new_text)
              
              # Write back all content
              with open(file_path, "w") as file:
                  file.write("\n".join(new_lines) + "\n")
          '

      
      - name: Update version number
        run: |
          python -c '
          import os
          import re
          
          # Get new version from workflow input
          new_version = "${{ github.event.inputs.new_version }}"
          
          # Read the file from target repository
          file_path = "docker-jenkins-stack/jenkins-master/Dockerfile"
          with open(file_path, "r") as file:
              content = file.read()
          
          # Use regex to replace everything after the colon while keeping "old-text:"
          new_content = re.sub(r"jenkins-master-docker:[\d.]+", f"jenkins-master-docker:{new_version}", content)
          
          # Write back to file
          with open(file_path, "w") as file:
              file.write(new_content)
          '
          
      - name: Check for changes
        id: check_changes
        working-directory: docker-jenkins-stack
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT
          
      - name: Create Pull Request
        if: steps.check_changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          path: docker-jenkins-stack
          commit-message: "Update version to ${{ github.event.inputs.new_version }}"
          title: "Version Update: ${{ github.event.inputs.new_version }}"
          body: |
            Automated version update:
            - Updated version from jenkins-master-docker:*.*.* to jenkins-master-docker:${{ github.event.inputs.new_version }}
            
            This PR was automatically generated by GitHub Actions.
          branch: version-update
          base: main  # Change this to your default branch if different
          delete-branch: true
